# Generated by Django 5.1.4 on 2024-12-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(max_length=50, unique=True)),
                ('pseudonimo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_libro', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(blank=True, max_length=50, null=True)),
                ('resena', models.TextField(blank=True, null=True)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Novela'), (2, 'Poesía'), (3, 'Cuentos'), (4, 'Filosofía'), (5, 'Historia')])),
                ('portada', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('estado_libro', models.PositiveSmallIntegerField(choices=[(1, 'Ingresado'), (2, 'Disponible'), (3, 'Reservado'), (4, 'Prestado'), (5, 'Devuelto'), (6, 'Pendiente'), (7, 'Perdido'), (8, 'En reparación')], default=1)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='AutorPorLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.libro')),
            ],
            options={
                'unique_together': {('libro', 'autor')},
            },
        ),
    ]
