# Generated by Django 5.1.4 on 2024-12-17 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_detallereserva'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallereserva',
            unique_together={('reserva', 'libro')},
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_atraso', models.PositiveSmallIntegerField(default=1)),
                ('monto_multa', models.PositiveIntegerField(default=0)),
                ('detalle_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.detallereserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'detalle_reserva')},
            },
        ),
    ]
