# Generated by Django 5.1.4 on 2024-12-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_autor_autor_nombre_idx_autor_autor_pseudonimo_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autorporlibro',
            index=models.Index(fields=['libro'], name='AutorPorLibro_libro_idx'),
        ),
        migrations.AddIndex(
            model_name='autorporlibro',
            index=models.Index(fields=['autor'], name='AutorPorLibro_autor_idx'),
        ),
    ]
