# Generated by Django 5.1.4 on 2024-12-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_autorporlibro_autorporlibro_libro_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='Reserva_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_compromiso'], name='Reserva_feccom_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_max_retiro'], name='Reserva_fecmaxret_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado_reserva'], name='Reserva_estado_idx'),
        ),
    ]
