# Generated by Django 5.1.4 on 2024-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_reserva_reserva_usuario_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detallereserva',
            index=models.Index(fields=['reserva'], name='DetalleReserva_reserva_idx'),
        ),
        migrations.AddIndex(
            model_name='detallereserva',
            index=models.Index(fields=['libro'], name='DetalleReserva_libro_idx'),
        ),
        migrations.AddIndex(
            model_name='detallereserva',
            index=models.Index(fields=['estado_detalle_reserva'], name='DetalleReserva_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='detallereserva',
            index=models.Index(fields=['fecha_max_devolucion'], name='DetalleReserva_fecmaxdev_idx'),
        ),
    ]
