# Generated by Django 5.1.4 on 2024-12-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_detallereserva_detallereserva_reserva_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='multa',
            index=models.Index(fields=['usuario'], name='Multa_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='multa',
            index=models.Index(fields=['detalle_reserva'], name='Multa_detalle_idx'),
        ),
        migrations.AddIndex(
            model_name='multa',
            index=models.Index(fields=['dias_atraso'], name='Multa_diasatraso_idx'),
        ),
        migrations.AddIndex(
            model_name='multa',
            index=models.Index(fields=['monto_multa'], name='Multa_monto_idx'),
        ),
    ]
