# Generated by Django 5.1.4 on 2024-12-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_app', '0010_multa_multa_usuario_idx_multa_multa_detalle_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rut'], name='Usuario_rut_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='Usuario_rol_idx'),
        ),
    ]
