# Generated by Django 5.1.4 on 2024-12-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_alter_usuario_options_usuario_usuario_rut_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='autor',
            name='Autor_nombre_idx',
        ),
        migrations.RemoveIndex(
            model_name='autor',
            name='Autor_pseudonimo_idx',
        ),
        migrations.RemoveIndex(
            model_name='editorial',
            name='Editorial_nombre_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='Usuario_rut_idx',
        ),
    ]
