# Generated by Django 5.1.4 on 2024-12-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_autorporlibro_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallereserva',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='multa',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='detallereserva',
            constraint=models.UniqueConstraint(fields=('reserva', 'libro'), name='DetalleReserva_reservalibro_un'),
        ),
        migrations.AddConstraint(
            model_name='multa',
            constraint=models.UniqueConstraint(fields=('usuario', 'detalle_reserva'), name='Multa_usuariodetalle_un'),
        ),
    ]
